package trunfopokemon;

import CrudRecorde.PlayerDAO;

public class InterfacePrincipal extends javax.swing.JFrame {
    
    Utilidade util = new Utilidade();
    
    public InterfacePrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BotaoJogar = new javax.swing.JButton();
        BotaoRecorde = new javax.swing.JButton();
        BotaoComoJogar = new javax.swing.JButton();
        Evento = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Trunfo ");

        BotaoJogar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotaoJogar.setText("Jogar");
        BotaoJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoJogarActionPerformed(evt);
            }
        });

        BotaoRecorde.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotaoRecorde.setText("Recorde");
        BotaoRecorde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoRecordeMouseClicked(evt);
            }
        });
        BotaoRecorde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRecordeActionPerformed(evt);
            }
        });

        BotaoComoJogar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotaoComoJogar.setText("Como Jogar");
        BotaoComoJogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoComoJogarMouseClicked(evt);
            }
        });
        BotaoComoJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoComoJogarActionPerformed(evt);
            }
        });

        Evento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Evento.setToolTipText("");
        Evento.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Evento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Evento.setMaximumSize(new java.awt.Dimension(200, 250));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/png-clipart-pokemon-logo-pokemon-logo.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BotaoRecorde, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotaoComoJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotaoJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addComponent(Evento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotaoJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotaoRecorde, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotaoComoJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Evento, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoJogarActionPerformed
        util.jogo(true);        
        util.menu(false);
    }//GEN-LAST:event_BotaoJogarActionPerformed

    private void BotaoRecordeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRecordeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoRecordeActionPerformed

    private void BotaoComoJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoComoJogarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoComoJogarActionPerformed

    private void BotaoComoJogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoComoJogarMouseClicked
        Evento.setText("<html>você recebe uma carta e o computador outra,<br/>você tera que escolher um atributo para comparar com a carta do computador,<br/>o numero que for maior ganha! se você perder 3 vidas o jogo acaba!</html>");
    }//GEN-LAST:event_BotaoComoJogarMouseClicked

    private void BotaoRecordeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoRecordeMouseClicked
        PlayerDAO Pd = new PlayerDAO();
        Evento.setText(Pd.getRecordes());
    }//GEN-LAST:event_BotaoRecordeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BotaoComoJogar;
    public static javax.swing.JButton BotaoJogar;
    public static javax.swing.JButton BotaoRecorde;
    public static javax.swing.JLabel Evento;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
